# docker build -t nightscout-ps1-build:debian -f Dockerfile.debian .
# docker run -it --rm -v $PWD/packed:/packed nightscout-ps1-build:debian
FROM ubuntu

RUN apt-get update && apt-get install -y \
  build-essential \
  python

COPY . /nightscout-ps1

WORKDIR /nightscout-ps1

CMD make && strip ./out/Default/nightscout-ps1 && cp -v ./out/Default/nightscout-ps1 /packed/
